version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_ARGS="--requirepass PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru"
      
    depends_on:
      - redis-server

  redis-server:
    image: redis/redis-stack:latest
    container_name: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"
  